from __future__ import annotations

from pathlib import Path

from mapir.export import blender_exporter, obj_exporter
from mapir.utils.io import load_ir


def test_obj_export_scene_has_vertices_and_faces(scene_files: list[Path]) -> None:
    target = next(f for f in scene_files if "warehouse" in f.name)
    text = obj_exporter.export(load_ir(target))
    assert "v " in text
    assert "f " in text
    assert "o scene_floor" in text
    # at least one zone and one object should appear
    assert any(line.startswith("o zone_") for line in text.splitlines())
    assert any(line.startswith("o obj_") for line in text.splitlines())


def test_obj_export_world_has_districts(world_files: list[Path]) -> None:
    target = next(f for f in world_files if "jisso" in f.name)
    text = obj_exporter.export(load_ir(target))
    assert "o world_ground" in text
    assert "o district_sotonbori" in text
    assert "o slot_minato_container_yard" in text


def test_blender_script_imports_bpy_and_runs(tmp_path: Path, scene_files: list[Path]) -> None:
    target = next(f for f in scene_files if "warehouse" in f.name)
    script = blender_exporter.export(load_ir(target))
    assert script.startswith('"""Auto-generated by MapIR.')
    assert "import bpy" in script
    assert "def main():" in script
    # Confirm it parses as Python
    compile(script, "blender_export.py", "exec")


def test_blender_script_for_world_parses(world_files: list[Path]) -> None:
    target = next(f for f in world_files if "jisso" in f.name)
    script = blender_exporter.export(load_ir(target))
    assert "import bpy" in script
    compile(script, "blender_world.py", "exec")
