from __future__ import annotations

from pathlib import Path

from mapir.core.models import SceneIR, WorldIR
from mapir.export import blender_exporter, obj_exporter
from mapir.utils.io import load_ir


def _pick_interior(scene_files: list[Path]) -> Path:
    """Prefer an interior demo (which we populate with cover objects)."""
    for f in scene_files:
        if "interior" in f.name.lower():
            return f
    return scene_files[0]


def test_obj_export_scene_has_vertices_and_faces(scene_files: list[Path]) -> None:
    target = _pick_interior(scene_files)
    ir = load_ir(target)
    assert isinstance(ir, SceneIR)
    text = obj_exporter.export(ir)
    assert "v " in text
    assert "f " in text
    assert "o scene_floor" in text
    # At least one zone and one object should appear in v0.5 demos
    # (build_demo_fixtures.py emits ≥ 3 cover objects per scene).
    assert any(line.startswith("o zone_") for line in text.splitlines())
    assert any(line.startswith("o obj_") for line in text.splitlines())


def test_obj_export_world_has_districts(world_files: list[Path]) -> None:
    assert world_files
    target = world_files[0]
    ir = load_ir(target)
    assert isinstance(ir, WorldIR)
    text = obj_exporter.export(ir)
    assert "o world_ground" in text
    # Each district is emitted as ``o district_<id>``; pick any.
    assert any(line.startswith("o district_") for line in text.splitlines())
    # Each scene slot is emitted as ``o slot_<id>``.
    assert any(line.startswith("o slot_") for line in text.splitlines())


def test_blender_script_imports_bpy_and_runs(tmp_path: Path, scene_files: list[Path]) -> None:
    target = _pick_interior(scene_files)
    script = blender_exporter.export(load_ir(target))
    assert script.startswith('"""Auto-generated by MapIR.')
    assert "import bpy" in script
    assert "def main():" in script
    # Confirm it parses as Python
    compile(script, "blender_export.py", "exec")


def test_blender_script_for_world_parses(world_files: list[Path]) -> None:
    assert world_files
    target = world_files[0]
    script = blender_exporter.export(load_ir(target))
    assert "import bpy" in script
    compile(script, "blender_world.py", "exec")
