"""Markdown design report — bundles structural validation + design warnings.

The report cites rule ids so reviewers can trace each note back to
``guides/design_rules.json``.
"""

from __future__ import annotations

from ..core.models import SceneIR, WorldIR
from ..core.validation import ValidationReport
from ..generation.layout import GeneratedLayout
from .design_rules import load_design_rules
from .validators import DesignReport


def build_design_report_markdown(
    ir: WorldIR | SceneIR,
    layout: GeneratedLayout | None,
    structural: ValidationReport,
    design: DesignReport,
) -> str:
    rules = {r.id: r for r in load_design_rules().rules}
    parts: list[str] = []
    parts.append(f"# Design report — {getattr(ir, 'name', '?')}\n")
    parts.append(f"_Generated by MapIR v0.5_\n")

    # Summary
    parts.append("## Summary\n")
    parts.append(
        f"- IR type: **{ir.ir_type.value if hasattr(ir, 'ir_type') else '?'}**"
    )
    if isinstance(ir, WorldIR):
        parts.append(
            f"- districts: {len(ir.districts)} · roads: {len(ir.roads)} · "
            f"scene slots: {len(ir.scene_slots)} · POIs: {len(ir.pois)}"
        )
    else:
        parts.append(
            f"- zones: {len(ir.zones)} · entrances: {len(ir.entrances)} · "
            f"objects: {len(ir.objects)} · markers: {len(ir.gameplay_markers)}"
        )
    if layout is not None:
        parts.append(
            f"- generated layout: {len(layout.roads)} road(s), "
            f"{len(layout.parcels)} parcel(s), {len(layout.buildings)} building(s), "
            f"{len(layout.landmarks)} landmark(s), {len(layout.guidance_cues)} guidance cue(s)"
        )
    parts.append(
        f"- structural: **{'OK' if structural.is_valid else 'FAIL'}** · "
        f"errors={len(structural.errors)} · warnings={len(structural.warnings)}"
    )
    parts.append(
        f"- design rules: errors={len(design.errors())} · "
        f"warnings={len(design.warnings_only())} · infos={len(design.infos())}\n"
    )

    # Structural section
    if structural.errors or structural.warnings:
        parts.append("## Structural validation\n")
        for issue in structural.errors + structural.warnings:
            parts.append(f"- **{issue.severity.value.upper()}** `{issue.code}` — {issue.message}")
        parts.append("")

    # Design rules section, grouped by category
    if design.warnings:
        parts.append("## Design-aware findings\n")
        for category, items in design.by_category().items():
            parts.append(f"### {category.value}\n")
            for w in items:
                rule_text = ""
                if w.rule_id and w.rule_id in rules:
                    r = rules[w.rule_id]
                    rule_text = f" _({r.name} — {r.source_note})_"
                parts.append(
                    f"- **{w.severity.value.upper()}** `{w.code}` — {w.message}"
                    f"{rule_text}"
                )
            parts.append("")
    else:
        parts.append("## Design-aware findings\n")
        parts.append("_No design rule violations detected._\n")

    return "\n".join(parts) + "\n"
